version: "3"

services:
  nodejs:
    container_name: nodejs_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - PORT=3001
    command: ["npm", "start"]
    restart: always
