version: "3"

services:
  nodejs:
    container_name: nodejs_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PORT=3001
    command: ["node", "index.js"]  # Usa node diretamente para rodar o index.js
    restart: always
